ARG BASE_IMAGE=open-webui:v011-hotfix-4934cdf59bbf
FROM ${BASE_IMAGE}

ARG BASE_IMAGE
ARG HOTPATCH_SOURCE_COMMIT
LABEL org.opencontainers.image.revision="${HOTPATCH_SOURCE_COMMIT}" \
      io.openwebui.hotpatch.base-image="${BASE_IMAGE}" \
      io.openwebui.hotpatch.scope="v0.11-pre-v011-answer-typography-sidebar-cleanup"

ENV WEBUI_BUILD_VERSION="${HOTPATCH_SOURCE_COMMIT}"

RUN rm -rf -- /app/build
COPY --chown=0:0 build /app/build

RUN test -s /app/build/index.html \
    && test -s /app/build/_app/version.json \
    && grep -F -q "${HOTPATCH_SOURCE_COMMIT}" /app/build/_app/version.json \
    && grep -R -F -q 'max-width:58rem' /app/build/_app/immutable/assets \
    && grep -R -F -q 'white-space:pre-line' /app/build/_app/immutable/assets \
    && grep -R -F -q 'max-width:none' /app/build/_app/immutable/assets \
    && grep -R -F -q 'border-inline-start-width:2px' /app/build/_app/immutable/assets \
    && grep -R -F -q 'margin-block:calc(var(--spacing,.25rem) * 0)' /app/build/_app/immutable/assets \
    && ! grep -R -F -q 'sidebar-openclaw-button' /app/build/_app/immutable
